name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
      forge-1-20-1:
        description: '1.20.1 Forge'
        required: true
        type: boolean
      neo-1-20-1:
        description: '1.20.1 NeoForge'
        required: true
        type: boolean
      fabric-1-20-1:
        description: '1.20.1 Fabric'
        required: true
        type: boolean
      fabric-1-20-4:
        description: '1.20.4 Fabric'
        required: true
        type: boolean
      fabric-1-20-6:
        description: '1.20.6 Fabric'
        required: true
        type: boolean
      fabric-1-21:
        description: '1.21 Fabric'
        required: true
        type: boolean

jobs:
  publish-to-modrinth:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ${{ github.workspace }}/*.mrpack

      - name: Zip forge/1.20.1
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/forge/1.20.1
          dest: ExceptionallyOptimized ${{ inputs.version }}+forge.1.20.1.mrpack

      - name: Zip neo/1.20.1
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/neo/1.20.1
          dest: ExceptionallyOptimized ${{ inputs.version }}+neo.1.20.1.mrpack

      - name: Zip fabric/1.20.1
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.20.1
          dest: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.1.mrpack

      - name: Zip fabric/1.20.4
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.20.4
          dest: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.4.mrpack

      - name: Zip fabric/1.20.6
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.20.6
          dest: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.6.mrpack

      - name: Zip fabric/1.21
        uses: vimtor/action-zip@v1.2
        with:
          files: modrinth/fabric/1.21
          dest: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.21.mrpack

      - if: ${{ inputs.forge-1-20-1 }}
        name: Publish forge/1.20.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Wn64OeXh
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            ${{ github.workspace }}/*forge.1.20.1.mrpack

          name: ExceptionallyOptimized ${{ inputs.version }}+forge.1.20.1
          version: ${{ inputs.version }}+forge.1.20.1
          version-type: release
          changelog-file: modrinth/forge/1.20.1/CHANGELOG.md

          loaders: |
            forge
          game-versions: |
            1.20.1
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.neo-1-20-1 }}
        name: Publish neo/1.20.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Wn64OeXh
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            ${{ github.workspace }}/*neo.1.20.1.mrpack

          name: ExceptionallyOptimized ${{ inputs.version }}+neo.1.20.1
          version: ${{ inputs.version }}+neo.1.20.1
          version-type: release
          changelog-file: modrinth/neo/1.20.1/CHANGELOG.md

          loaders: |
            neoforge
          game-versions: |
            1.20.1
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.fabric-1-20-1 }}
        name: Publish fabric/1.20.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Wn64OeXh
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            ${{ github.workspace }}/*fabric.1.20.1.mrpack

          name: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.1
          version: ${{ inputs.version }}+fabric.1.20.1
          version-type: release
          changelog-file: modrinth/fabric/1.20.1/CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            1.20.1
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.fabric-1-20-4 }}
        name: Publish fabric/1.20.4
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Wn64OeXh
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            ${{ github.workspace }}/*fabric.1.20.4.mrpack

          name: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.4
          version: ${{ inputs.version }}+fabric.1.20.4
          version-type: release
          changelog-file: modrinth/fabric/1.20.4/CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            1.20.4
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.fabric-1-20-6 }}
        name: Publish fabric/1.20.6
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Wn64OeXh
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            ${{ github.workspace }}/*fabric.1.20.6.mrpack

          name: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.6
          version: ${{ inputs.version }}+fabric.1.20.6
          version-type: release
          changelog-file: modrinth/fabric/1.20.6/CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            1.20.6
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.fabric-1-21 }}
        name: Publish fabric/1.21
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Wn64OeXh
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            ${{ github.workspace }}/*fabric.1.21.mrpack

          name: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.21
          version: ${{ inputs.version }}+fabric.1.21
          version-type: release
          changelog-file: modrinth/fabric/1.21/CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            1.21
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

  publish-to-curseforge:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Zip forge/1.20.1
        uses: vimtor/action-zip@v1.2
        with:
          files: curseforge/forge/1.20.1
          dest: ExceptionallyOptimized ${{ inputs.version }}+forge.1.20.1.zip

      - name: Zip neo/1.20.1
        uses: vimtor/action-zip@v1.2
        with:
          files: curseforge/neo/1.20.1
          dest: ExceptionallyOptimized ${{ inputs.version }}+neo.1.20.1.zip

      - name: Zip fabric/1.20.6
        uses: vimtor/action-zip@v1.2
        with:
          files: curseforge/fabric/1.20.6
          dest: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.6.zip

      - name: Zip fabric/1.21
        uses: vimtor/action-zip@v1.2
        with:
          files: curseforge/fabric/1.21
          dest: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.21.zip

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ${{ github.workspace }}/*.zip

      - if: ${{ inputs.forge-1-20-1 }}
        name: Publish forge/1.20.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1049933
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            ${{ github.workspace }}/*forge.1.20.1.zip

          name: ExceptionallyOptimized ${{ inputs.version }}+forge.1.20.1
          version: ${{ inputs.version }}+forge.1.20.1
          version-type: release
          changelog-file: modrinth/forge/1.20.1/CHANGELOG.md

          loaders: |
            forge
          game-versions: |
            1.20.1
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.neo-1-20-1 }}
        name: Publish neo/1.20.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1049933
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            ${{ github.workspace }}/*neo.1.20.1.zip

          name: ExceptionallyOptimized ${{ inputs.version }}+neo.1.20.1
          version: ${{ inputs.version }}+neo.1.20.1
          version-type: release
          changelog-file: modrinth/neo/1.20.1/CHANGELOG.md

          loaders: |
            neoforge
          game-versions: |
            1.20.1
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.fabric-1-20-6 }}
        name: Publish fabric/1.20.6
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1049933
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            ${{ github.workspace }}/*fabric.1.20.6.zip

          name: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.20.6
          version: ${{ inputs.version }}+fabric.1.20.6
          version-type: release
          changelog-file: modrinth/fabric/1.20.6/CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            1.20.6
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - if: ${{ inputs.fabric-1-21 }}
        name: Publish fabric/1.21
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1049933
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            ${{ github.workspace }}/*fabric.1.21.zip

          name: ExceptionallyOptimized ${{ inputs.version }}+fabric.1.21
          version: ${{ inputs.version }}+fabric.1.21
          version-type: release
          changelog-file: modrinth/fabric/1.21/CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            1.21
          game-version-filter: releases

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
